name: Run

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  reuse_build:
    uses: gamemann/XDP-Firewall/.github/workflows/build.yml@master
  run:
    needs: reuse_build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: run XDP FW with help menu
      run: xdpfw -h
