name: Run

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: use build workflow
      uses: ./workflows/build@v2
    - name: run XDP FW with help menu
      run: xdpfw -h
