name: Run

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  reuse_build:
    uses: gamemann/XDP-Firewall/.github/workflows/build.yml@master
  run:
    needs: reuse_build
    runs-on: ubuntu-latest
    steps:
    - name: Download artifact from Build workflow
      uses: actions/download-artifact@master
      with:
        name: build-output
    - name: run XDP FW with help menu
      run: ./build/xdpfw -h
