name: Run

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  with:
    uses: gamemann/XDP-Firewall/.github/workflows/build.yml@main
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: run XDP FW with help menu
      run: xdpfw -h
